blog_package/blog/urls.py
from django.conf.urls import include, url
from django.contrib.auth.views import login, logout
from blog.views import home, makepost

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'login/$',
        login,
        name='Login'),
    url(r'logout/$',
        logout,
        {'next_page': 'blog:home'},
        name='Logout'),
    url(r'create-post/$', makepost, name='create-post'),
]

blog_package/blog_package/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^administration/lance/',
        include(admin.site.urls)),
    url(r'^blog/',
        include('blog.urls',
                namespace='blog')),
    url(r'^', include('portfolio.urls',
                      namespace='portfolio')),
    url(r'^uploads/',
                      include('stickyuploads.urls')),
]

blog_package/portfolio/urls.py
from django.conf.urls import include, url
from .views import portfolio, resume, projects, edgar

urlpatterns = [
    url(r'^$', portfolio,  name='portfolio'),
    url(r'^resume/$', resume, name='resume'),
    url(r'^projects/$', projects, name='projects'),
    url(r'^edgar_project/', edgar, name='edgar')

]

blog_package/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from PIL import Image  # this is needed for the models.ImageField to work

# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField(max_length=100, blank=False)
    body = models.ManyToManyField('Paragraph')
    date = models.DateField(auto_now_add=True)
    photos = models.ManyToManyField('Photo', blank=True)


class Photo(models.Model):
    blog_post = models.ForeignKey(Post, blank=True, null=True)
    title = models.CharField(max_length=30, blank=True, null=True)
    photo = models.ImageField(upload_to='profile_image/%Y/%m/%d', blank=True)
    date = models.DateField(auto_now_add=True)
    number = models.IntegerField(blank=True, null=True)


class Paragraph(models.Model):
    blog_post = models.ForeignKey(Post)
    paragraph = models.TextField(blank=True, null=True)
    number = models.IntegerField(blank=True, null=True)

blog_package/portfolio/models.py
from django.db import models

# Create your models here.

blog_package/blog/forms.py
from django import forms
from PIL import Image
from PIL import Image  # this is needed for the models.ImageField to work
from stickyuploads.widgets import StickyUploadWidget


class PhotoForm(forms.Form):
    image = forms.ImageField(label='Please upload a profile image',
                            required=False,
                            widget=StickyUploadWidget,
                            error_messages={'invalid_file': 'Please upload an image'}
                            )

blog_package/blog/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
# Create your views here.


def home(request):
    return render(request, 'blog/index.html')


def makepost(request):
    return render(request, 'blog/post-creation.html')

blog_package/portfolio/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

def portfolio(request):
    return render(request, 'portfolio/portfolio.html')


def resume(request):
    return render(request, 'portfolio/resume.html')


def projects(request):
    return render(request, 'portfolio/projects.html')

def edgar(request):
    return render(request, 'portfolio/edgar_project.html')

blog_package/blog/templates/blog/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Lance's Blog</title>
</head>
<body>




{% block body %}
{% endblock %}
</body>
</html>

blog_package/blog/templates/blog/post-creation.html
{% extends 'blog/base.html' %}
{% block body %}




{% endblock %}

blog_package/portfolio/templates/portfolio/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Lance K Rogers</title>
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/grayscale.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">





{% block head %}
{% endblock %}
    <meta charset="UTF-8">
    <title></title>
</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                    <i class="fa fa-play-circle"></i>  <span class="light">Lance</span> Rogers
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#portfolio">Portfolio</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

{% block body %}


{% endblock %}
<!-- Footer -->
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; LanceKRogers.com 2015</p>
        </div>
    </footer>

  <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'js/jquery.easing.min.js' %}"></script>


    <!-- Custom Theme JavaScript -->
    <script src="{% static 'js/grayscale.js' %}"></script>


</body>
</html>

blog_package/portfolio/templates/portfolio/non-port-base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Lance K Rogers</title>

     <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/grayscale.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">





{% block head %}
{% endblock %}
    <meta charset="UTF-8">
    <title>Lance K Rogers</title>
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />
</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="{% url 'portfolio:portfolio' %}">
                    <i class="fa fa-play-circle"></i>  <span class="light">Lance</span> Rogers
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="{% url 'portfolio:portfolio' %}#about">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="{% url 'portfolio:portfolio' %}#portfolio">Portfolio</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="{% url 'portfolio:portfolio' %}#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

{% block body %}


{% endblock %}
<!-- Footer -->
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; LanceKRogers.com 2015</p>
        </div>
    </footer>

  <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'js/jquery.easing.min.js' %}"></script>


    <!-- Custom Theme JavaScript -->
    <script src="{% static 'js/grayscale.js' %}"></script>


</body>
</html>

blog_package/portfolio/templates/portfolio/portfolio.html
{% extends 'portfolio/base.html' %}


{% block head %}

{% endblock %}

{% block body %}
    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">Lance Rogers</h1>
                        <p class="intro-text">Python Engineer<br></p>
                        <a href="#about" class="btn btn-circle page-scroll">
                            <i class="fa fa-angle-double-down animated"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- About Section -->
    <section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>About</h2>
                <h4 align="Left">Curiosity</h4>
                <p>
                    Growing up I liked to figure out how things worked.
                    I'd take apart everything I could and figure out how to put it
                    back together.  This curiosity led me to trying to fix
                    anything that breaks.  From cars and lawnmowers to computers
                    and cell phones, when they break I try to fix them.
                </p>
                <p>

                </p>
                <h4 align="right">Education</h4>
                <p>
                    In high school I was continually
                    told that if I want to do something I have to have a degree in it.
                    I eventually took it as truth and went to college.  During college
                    I was still learning more outside the classroom than in it.  With
                    the cost of school I decided to take the year off to try and pay for school.
                    I worked a lot and learned a lot.  After a few months I got a job that paid enough
                    for me to quit my part time job and spend my days off inventing and learning.  I had the
                    need for an App that I couldn't find, so I decided to build it.  I started to teach myself
                    how to program.  After learning SQL, I started teaching myself Java.  After
                    a few weeks I realized I needed to make it my full time job, so I went to the Iron Yard.
                    They had a Python Engineering class starting in a month.  I decided to sign up so it would
                    be easier to learn other programming languages afterward.  I signed up and
                    started a campaign on <a href="http://igg.me/at/4j3KqB4PDvk" target="_blank">IndieGoGO</a> to help with
                    the cost of living.  With my total on and off site donations, I was able to raise more than my
                    $3000 need.
                    The Iron Yard was challenging, but well worth it.  By the end of the program I was able
                    to build Cleff, a social network for musicians.

                </p>
                <h4 align="left">Work</h4>
                <p>
                    Since a very young age I have had the desire to work.
                    At eight years old I mowed lawns, washed cars, and rounded up my cousins
                    to help me sell candy and whatever we could find on the side of the road.
                    By 15 I had my first real job working at a <a href="https://foodmarketmaker.com/uploads/71b6c019a0c3ca34687fdb0fa898551b.pdf" target="_blank">buffalo farm</a>.
                    Since then I have always had a strong work ethic. I have never been fired and have continued to
                    find extra work on my days off.  While at the Iron Yard I would work seven days a week, 12-16 hours
                    a day, since graduation my work ethic has become even better.
                 </p>
            </div>
        </div>
    </section>

    <!-- Download Section -->
    <section id="portfolio" class="content-section text-center">
        <div class="download-section">
            <div class="container">
                <div class="col-lg-8 col-lg-offset-2">
                    <h2>Portfolio</h2>
                    <hr ><br />
                    <ul class="list-inline banner-social-buttons">
                        <li>
                            <a href="#about" class="btn btn-default btn-lg">My Story</a>
                        </li>
                        <li>
                            <a href="{% url 'portfolio:resume' %}" class="btn btn-default btn-lg">Resume</a>
                        </li>
                        <li>
                            <a href="{% url 'portfolio:projects' %}" class="btn btn-default btn-lg">Projects</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Contact</h2>
                <hr ><br />
                <h3>864-567-9990</h3>


                <ul class="list-inline banner-social-buttons">
                    <li>
                        <a href="https://www.linkedin.com/in/lancekrogers" target="_blank" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                    </li>
                    <li>
                        <a href="https://github.com/lancekrogers" target="_blank" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                    </li>
                    <li>
                        <a href="mailto:lancekrogers@gmail.com" class="btn btn-default btn-lg">
                            <span class="network-name">E-Mail</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </section>



{% endblock %}

blog_package/portfolio/templates/portfolio/projects.html
{% extends 'portfolio/non-port-base.html' %}
{% block body %}
<br /> <br /><br /><br /><br /><br />
    <section class="text-center">

<div>

<div class="row">
            <div class="container">
        <div class="cleff">
  <div class="col-md-12"><h1>Cleff</h1><hr/></div>
     <p> Cleff is a social network for musicians.
         The app finds a users location and displays a stream of videos from musicians in their
         local area.  Users essentially build a music resume and post a video of them playing to be
         found.  The app also features two forums and a messaging system for communication which I built.
         This is the app I set out to build when I first started learning how to program and
         by the ninth week of the Iron Yard I felt I had the skills needed to build a prototype version,
         so I made it my final project.
     </p>
    <p><h4><a href="https://github.com/lancekrogers/music-network" target="_blank" class="btn btn-default btn-lg">
        Check Out The Code!</a></h4></p>
    </div> <!-- cleff -->
    <hr/>
    <h3>Tools</h3>
    <h6>Used in Cleff</h6>
<table class="toolstech">
    <tr>
    <td><h4>Django</h4></td>
    <td><h4>Python3</h4></td>
    </tr>
    <tr>
    <td><h4>Git</h4></td>
    <td><h4>POSTGRESQL</h4></td>
    <tr>

    <td><h4>HTML5</h4></td>
    <td><h4>CSS3</h4></td>
    </tr>
    <tr>

    <td><h4>Javascript</h4></td>
    <td><h4>jQuery</h4></td>
    </tr>
    <tr>


    <td><h4>Django Sticky Uploads</h4></td>
    <td><h4>Pillow</h4></td>
    </tr>
    <tr>
        <td><h4><a target="_blank" href="https://github.com/lancekrogers/django-geoposition" target="_blank">Django-Geoposition</a></h4></td>
        <td><h4>Geo-Django</h4></td>
    </tr>
    <tr>

    <td><h4>Bootstrap</h4></td>
    <td><h4>Ajax</h4></td>
    </tr>
    <tr>

    <td><h4>Elastic Search</h4></td>
    <td><h4>Haystack</h4></td>
    </tr>


</table>
</div>
    </div>
    </div></div>
        </section><br /><br />

<section class="text-center">
<div class="row">
    <div class="container">


  <div class="col-md-6">
      <hr />
      <h1>Edgerdb</h1><hr/>
    <p>
        This is a python package I built for an ongoing algorithmic trading program I am working on.  This
        package makes it easy to create, maintain, and analize SEC filings using python.
    </p>

    <p><h4><a href="{% url 'portfolio:edgar' %}" target="_blank" class="btn btn-default btn-lg">
        Checkout the Jupyter Notebook version</a></h4></p>
    <p><h4><a href="https://github.com/lancekrogers/edgerdb" target="_blank" class="btn btn-default btn-lg">
        Checkout the Repo</a></h4></p>
    <hr/>
    <h3>Tools</h3>
    <h6>Used in Edgerdb</h6>
<table class="toolstech">
    <tr>
    <td><h4>Python</h4></td>
    <td><h4>ftplib</h4></td>
    </tr>
    <tr>
   <td><h4>POSTGRESQL</h4></td>
   <td><h4>www.sec.gov</h4></td>
    </tr>


</table>
</div>





  <div class="col-md-6">
      <hr />
      <h1>Restaurant App</h1><hr/>
    <p>This Restaurant App was an Iron Yard group assignment that was built 1 week after being introduced to Django.</p> <p>
    The App allows a user to place orders, allows the kitchen to view and complete orders, and allows the owner to customize the menus.
</p>
    <p><h4><a href="http://ec2-52-11-76-189.us-west-2.compute.amazonaws.com/" target="_blank" class="btn btn-default btn-lg">
        See it Live!</a></h4></p>
    <p><h4><a href="https://github.com/lancekrogers/team-a-restaurant" target="_blank" class="btn btn-default btn-lg">
        Checkout the Code</a></h4></p>
    <hr/>
    <h3>Tools</h3>
    <h6>Used in Restaurant App</h6>
<table class="toolstech">
    <tr>
    <td><h4>Django</h4></td>
    <td><h4>Python</h4></td>
    </tr>
    <tr>
    <td><h4>Git</h4></td>
    <td><h4>Bootstrap</h4></td>
    </tr>
    <tr>

    <td><h4>HTML5</h4></td>
    <td><h4>CSS3</h4></td>
    </tr>
    <tr>
    </tr>

</table>



</div>
    </div>

    </div>
    </div>
    </div>

    <br />
    <br />




</section>








{% endblock %}

blog_package/portfolio/templates/portfolio/resume.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Lance K Rogers Resume</title>
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/grayscale.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">






    <meta charset="UTF-8">
    <title></title>
</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="{% url 'portfolio:portfolio' %}">
                    <i class="fa fa-play-circle"></i>  <span class="light">Lance</span> Rogers
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#objectives">Objectives</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#skills">Skills</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#education">Education</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#experience">Work Experience</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="{% url 'portfolio:portfolio' %}#portfolio">Portfolio</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="{% url 'portfolio:portfolio' %}#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

  <!-- Intro Header -->
    <header class="intro2">
        <div class="intro2-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand2-heading">Resume</h1>
                        <a href="#objectives" class="btn btn-circle page-scroll" >
                            <i class="fa fa-angle-double-down animated"></i>
                        </a>

                    </div>
                </div>
            </div>
        </div>
    </header>



<!-- Objectives Section -->
    <section id="objectives" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <hr />
                <table class="skilltable">
                    <tr>
                        <td>
                            <div class="contact-info">
                                Lance Kincaid Rogers<br/>
                                lancekrogers@gmail.com<br/>
                                (864)-567-9990
                            </div>
                        </td>

                </table>
                <hr/>
                <br /><br /><br />

                <h2>Objectives</h2>
                <div>
                    <p>
                        Land a role as a software engineer
                    <p>

                    </p>
                    <p>
                        Work heavily with data and machine learning
                    </p>
                    <p>
                        Bring new things into the world
                    </p>
                </div>
            </div>
        </div>
    </section>

<!-- Skills Section -->
    <section id="skills" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Skills</h2>
                <table class="skilltable contact-info">
                   <tr>
                        <td>Python</td>
                        <td>Django</td>
                        <td>Rest-Api</td>
                    </tr>
                    <tr>
                        <td>CSS3</td>
                        <td>jQuery</td>
                        <td>HTML5</td>
                    </tr>
                    <tr>
                        <td>Scikit-Learn</td>
                        <td>Pandas</td>
                        <td>Matplotlib</td>
                    </tr>
                    <tr>
                        <td>Numpy</td>
                        <td>Git</td>
                        <td>AWS</td>
                    </tr>
                    <tr>
                        <td>SQL</td>
                        <td>Postgres</td>
                        <td>Oracle</td>
                    </tr>
                    <tr>
                        <td>Linux</td>
                        <td>Unix</td>
                        <td>Windows</td>
                    </tr>
                </table>
            </div>
        </div>
    </section>

<!-- Education Section -->
    <section id="education" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Education</h2>
                <p>
                    <a class="a-font-overide" target="_blank" href="http://theironyard.com/">The Iron Yard Academy</a>
                    <br />Python Engineering
                    <br />Graduated 2015
                </p><br />
                <p>
                    <a class="a-font-overide" target="_blank" href="http://www.andersonuniversity.edu/arts-sciences">Anderson University</a><br />
                    Biology <br />
                    2013-2014
                </p><br />
                <p>
                    <a class="a-font-overide" target="_blank" href="http://www.greenville.k12.sc.us/hillcrest/">Hillcrest High School</a>
                    <br />Graduated 2013
                </p><br />
            </div>
        </div>
    </section>

 <!-- Work Experience Section -->
    <section id="experience" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Work Experience</h2>
                <p>
                     <a class="a-font-overide" href="http://www.ssi-schaefer.us/about-us/about-us.html" target="_blank">SSI Schaefer</a> <br />
                    <span class="experience-description">Software Support Engineer<br />October 2015 - September 2016</span>
                </p>
                <p>
                    <a class="a-font-overide" href="http://www.formeld.com/en/company/" target="_blank">Formel D USA</a> <br />
                    <span class="experience-description">Online Reworker BMW MC<br />December 2014 - May 2015</span>
                </p>
                <p>
                    <a class="a-font-overide" href="http://www.larkinsontheriver.com/" target="_blank">Larkins on The River</a><br />
                    <span class="experience-description">Banquet Server<br />April 2013 - December 2014</span>

                </p>
            </div>
        </div>
    </section>



 <!-- Footer -->
    <footer>
        <div class="container text-center">
            <p>References are available upon <a href="{% url 'portfolio:portfolio' %}#contact">request</a></p><br />
            <br />
        </div>
        <div class="container text-center">
            <p>Copyright &copy; LanceKRogers.com 2015</p>
        </div>
    </footer>

   <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'js/jquery.easing.min.js' %}"></script>


    <!-- Custom Theme JavaScript -->
    <script src="{% static 'js/grayscale.js' %}"></script>


</body>
</html>